name: CD Pipeline

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Docker Compose
      uses: ndeloof/install-compose-action@v0.0.1
      
    - name: Build Docker image
      run: docker compose build
      
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set Docker image name
      id: image_name
      run: |
        # Default to a local tag if no DockerHub username is provided
        if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
          echo "IMAGE_TAG=myfitnessapp:latest" >> $GITHUB_ENV
        else
          echo "IMAGE_TAG=${{ secrets.DOCKERHUB_USERNAME }}/myfitnessapp:latest" >> $GITHUB_ENV
        fi
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: ${{ secrets.DOCKERHUB_USERNAME != '' && secrets.DOCKERHUB_TOKEN != '' }}
        tags: ${{ env.IMAGE_TAG }} 